name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
      env:
        QUICKCHECK_TESTS: 10000

